# Generated by Django 4.0.3 on 2022-04-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0003_remove_super_primary_ability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='super',
            name='powers',
            field=models.ManyToManyField(blank=True, default='', to='supers.power'),
        ),
    ]
