# Generated by Django 4.0.3 on 2022-04-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0004_alter_super_powers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='super',
            name='powers',
            field=models.ManyToManyField(default='', to='supers.power'),
        ),
    ]
